### PR TITLE
Fix error "bryglen/yii2-apns-gcm 1.0.2 requires duccio/apns-php dev-m…

### PR DESCRIPTION
**Pull request by sactre**
Fix error "bryglen/yii2-apns-gcm 1.0.2 requires duccio/apns-php dev-master -> no matching package found."

### CODE REVIEW

**Comment by bryglen** [comment]
does this working now? does the duccio/apns-php already have a version support?

**Comment by gunrajTSG** [comment]
still not working
    - bryglen/yii2-apns-gcm 1.0.2 requires duccio/apns-php dev-master -> no matching package found.

**Comment by nmdimas** [comment]
When pull request will be adopted?

**Comment by bryglen** [comment]
There is no version for Duccio/apns-php

https://packagist.org/packages/duccio/apns-php

**Comment by nmdimas** [comment]
But now repository bryglen/yii2-apns-gcm not work. 
We must look for a solution.

**Comment by bryglen** [comment]
I was able to add it to my composer.json. what is your issues?

**Comment by nmdimas** [comment]
on all my project a can't add.
For example :

composer require --prefer-dist bryglen/yii2-apns-gcm "1.0.2"

Your requirements could not be resolved to an installable set of packages.

 Problem 1
    - Installation request for bryglen/yii2-apns-gcm 1.0.2 -> satisfiable by bryglen/yii2-apns-gcm[1.0.2].
    - bryglen/yii2-apns-gcm 1.0.2 requires duccio/apns-php dev-master -> no matching package found.


On old my project a manually add  bryglen/yii2-apns-gcm "1.0.2"  to composer.json and than call composer install. Bu it is the bad way.

**Comment by bryglen** [comment]
try to add manually in your composer.json

**Comment by bryglen** [comment]
Added 1.0.1 in apns library

**Pull request closed without merging**
