### PR TITLE
update php_gcm/php_gcm lib

### PR DESCRIPTION
**Pull request by marcinskubala**
Old version php_gcm does not work with current GCM API.

### CODE REVIEW

**Comment by bryglen** [comment]
thanks

**Comment by bryglen** [comment]
This doesn't work. 1.1.1 is still using sendMulti. reverting it back

https://github.com/lkorth/php-gcm/tree/1.1.1

**Comment by marcinskubala** [comment]
I don't know what you're trying to say but the PHP_GCM 1.1.1 doesn't have sendMulti() implementation. I'm on my way to create a new project so I will do some tests if everything works fine and if there are any problems I will make a PR.

**Comment by bryglen** [comment]
1.1.1 has sendMulti()
https://github.com/lkorth/php-gcm/blob/1.1.1/src/PHP_GCM/Sender.php#L187

the master don't have sendMulti() which don't have any tags yet

**Comment by marcinskubala** [comment]
hi, you are right, sorry for that. The problem is that the 1.1.1 version doesn't work with google service:

https://developers.google.com/cloud-messaging/http-server-ref
"Multicast messages (sending to more than 1 registration tokens) are allowed using HTTP JSON format only."

That is why I need to use dev version of PHP_GCM.

I will make a working version of my fork and make a PR tomorrow. You will do whatever you want with it.

**Comment by bryglen** [comment]
ok thanks.

**Pull request merged**
